/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next/components/BCard')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BToastOrchestrator: typeof import('bootstrap-vue-next/components/BToast')['BToastOrchestrator']
    CardWrapper: typeof import('./src/components/CardWrapper.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Gauge: typeof import('./src/components/Gauge.vue')['default']
    LeftSideBar: typeof import('./src/components/LeftSideBar.vue')['default']
    MainGrid: typeof import('./src/components/MainGrid.vue')['default']
    PluginUI: typeof import('./src/components/PluginUI.vue')['default']
    ProjectListItem: typeof import('./src/components/ProjectListItem.vue')['default']
    TestGridItem: typeof import('./src/components/TestGridItem.vue')['default']
    VideoJsPlayer: typeof import('./src/components/VideoJsPlayer.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    WindowManager: typeof import('./src/components/WindowManager.vue')['default']
  }
}
