/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BToastOrchestrator: typeof import('bootstrap-vue-next/components/BToast')['BToastOrchestrator']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    LeftSideBar: typeof import('./src/components/LeftSideBar.vue')['default']
    PluginUI: typeof import('./src/components/PluginUI.vue')['default']
    ProjectListItem: typeof import('./src/components/ProjectListItem.vue')['default']
    VideoJsPlayer: typeof import('./src/components/VideoJsPlayer.vue')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    WindowManager: typeof import('./src/components/WindowManager.vue')['default']
  }
}
