

### Get static file
GET http://127.0.0.1:8888

### Get healthcheck
GET http://127.0.0.1:8888/api/healthcheck
Accept: application/json



### Get docs
GET http://127.0.0.1:8888/docs

### Get swagger.json
GET http://127.0.0.1:8888/openapi.json

### Load csv files
GET http://127.0.0.1:8888/api/v1/project/files/csv



### Load CSV File
POST http://127.0.0.1:8888/api/v1/player/load_csv
Content-Type: application/json

{
  "file_name": "recording_2024_04_24__12_05_33_mapping_trip_02.csv"
}

### Play Stream
POST http://127.0.0.1:8888/api/v1/player/play
Content-Type: application/json

{}

### Pause Stream
POST http://127.0.0.1:8888/api/v1/player/pause
Content-Type: application/json

{}

### Jump to Timestamp
POST http://127.0.0.1:8888/api/v1/player/toTimeStamp
Content-Type: application/json

{
  "timestamp": 12.5
}

### Get the data stream
WEBSOCKET ws://127.0.0.1:8888/ws/replay
Content-Type: application/json // Used for content highlighting only
