

### Get static file
GET http://127.0.0.1:8888

### Get healthcheck
GET http://127.0.0.1:8888/api/healthcheck
Accept: application/json



### Get docs
GET http://127.0.0.1:8888/docs

### Get swagger.json
GET http://127.0.0.1:8888/openapi.json

### Load csv files
GET http://127.0.0.1:8888/api/v1/project/files/csv


### Create new project 1
POST http://127.0.0.1:8888/api/v1/project/create
Content-Type: application/json

{
  "csv_file_name": "recording_2024_04_06__14_15_33.csv",
  "video_file_name": "2024-04-06 14-05-37-1-cropped.m4v",
  "driver_name": "Christian Murschall",
  "vehicle_name": "Audi TT",
  "route_name": "Ostsee-Ring"
}

### Create new project 2
POST http://127.0.0.1:8888/api/v1/project/create
Content-Type: application/json

{
  "csv_file_name": "recording_2024_04_17__16_44_14_mapping_trip_01.csv",
  "video_file_name": "2024-04-17 16-10-09 Mapping Trip 01-1.m4v",
  "driver_name": "Michael Schumacher",
  "vehicle_id": "Ferrari F1 2000",
  "route_name": "Monaco"
}



### Get Active Project
GET http://127.0.0.1:8888/api/v1/project/active

### Activate Project
POST http://127.0.0.1:8888/api/v1/project/activate/2

### Deactiveate  Project
POST http://127.0.0.1:8888/api/v1/project/deactivate


### Load CSV File
POST http://127.0.0.1:8888/api/v1/player/load_csv
Content-Type: application/json

{
  "file_name": "recording_2024_04_24__12_05_33_mapping_trip_02.csv"
}

### Play Stream
POST http://127.0.0.1:8888/api/v1/player/play
Content-Type: application/json

{}

### Pause Stream
POST http://127.0.0.1:8888/api/v1/player/pause
Content-Type: application/json

{}

### Jump to Timestamp
POST http://127.0.0.1:8888/api/v1/player/toTimeStamp
Content-Type: application/json

{
  "timestamp": 12.5
}

### Get the data stream
WEBSOCKET ws://127.0.0.1:8888/ws/replay
Content-Type: application/json // Used for content highlighting only
